package yarnlock

import (
	"os"
	"testing"

	"github.com/jdecool/dependency-diff-notes/internal/lockfile"
)

func TestParse(t *testing.T) {
	tests := []struct {
		name    string
		file    string
		want    lockfile.Lock
		wantErr bool
	}{
		{
			name: "classic: realistic lock file, scoped package, multiple spec keys collapse to one entry",
			file: "testdata/classic_realistic.lock",
			want: lockfile.Lock{
				Combined: true,
				Packages: []lockfile.Package{
					{Name: "@babel/code-frame", Version: "7.12.13"},
					{Name: "lodash", Version: "4.17.21"},
				},
			},
		},
		{
			name: "classic: git dependency reference extracted from resolved, registry tarball hash is not mistaken for one",
			file: "testdata/classic_git_dependency.lock",
			want: lockfile.Lock{
				Combined: true,
				Packages: []lockfile.Package{
					{Name: "libsignal", Version: "2.0.1", Reference: "11dbd962ea108187c79a7c46fe4d6f790e23da97"},
					{Name: "tooling", Version: "1.26.4", Reference: "978dc1c9680ef7d79f5f5c02c3439385d7937c39"},
				},
			},
		},
		{
			name: "classic: header only, no packages",
			file: "testdata/classic_empty.lock",
			want: lockfile.Lock{Combined: true},
		},
		{
			name: "berry: realistic lock file, name/version read from resolution and top-level version field",
			file: "testdata/berry_realistic.yaml",
			want: lockfile.Lock{
				Combined: true,
				Packages: []lockfile.Package{
					{Name: "@algolia/autocomplete-core", Version: "1.17.9"},
					{Name: "lodash", Version: "4.17.21"},
				},
			},
		},
		{
			name: "berry: git dependency reference extracted from the resolution locator's #commit=",
			file: "testdata/berry_git_dependency.yaml",
			want: lockfile.Lock{
				Combined: true,
				Packages: []lockfile.Package{
					{Name: "underscore", Version: "1.13.1", Reference: "cbb48b79fc1205aa04feb03dbc055cdd28a12652"},
				},
			},
		},
		{
			name: "berry: soft-linked workspace member is not reported as a dependency",
			file: "testdata/berry_workspace_link.yaml",
			want: lockfile.Lock{
				Combined: true,
				Packages: []lockfile.Package{
					{Name: "lodash", Version: "4.17.21"},
				},
			},
		},
		{
			name: "berry: metadata-only, no packages",
			file: "testdata/berry_empty.yaml",
			want: lockfile.Lock{Combined: true},
		},
		{
			name:    "berry: malformed YAML",
			file:    "testdata/berry_malformed.yaml",
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			data, err := os.ReadFile(tt.file)
			if err != nil {
				t.Fatalf("read fixture: %v", err)
			}

			got, err := Parse(data)

			if tt.wantErr {
				if err == nil {
					t.Fatalf("Parse() error = nil, want an error")
				}
				return
			}
			if err != nil {
				t.Fatalf("Parse() unexpected error: %v", err)
			}

			if got.Combined != tt.want.Combined {
				t.Errorf("Combined = %v, want %v", got.Combined, tt.want.Combined)
			}
			assertPackagesEqual(t, "Packages", got.Packages, tt.want.Packages)
		})
	}
}

func TestIsClassic(t *testing.T) {
	tests := []struct {
		name string
		data string
		want bool
	}{
		{
			name: "classic header present",
			data: "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\nfoo@^1.0.0:\n  version \"1.0.0\"\n",
			want: true,
		},
		{
			name: "berry header, no classic marker",
			data: "# This file is generated by running \"yarn install\" inside your project.\n# Manual changes might be lost - proceed with caution!\n\n__metadata:\n  version: 8\n",
			want: false,
		},
		{
			name: "empty content",
			data: "",
			want: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := isClassic([]byte(tt.data)); got != tt.want {
				t.Errorf("isClassic(%q) = %v, want %v", tt.data, got, tt.want)
			}
		})
	}
}

func TestPackageName(t *testing.T) {
	tests := []struct {
		name    string
		specKey string
		want    string
	}{
		{name: "unscoped", specKey: "lodash@^4.17.21", want: "lodash"},
		{name: "scoped", specKey: "@babel/code-frame@^7.12.13", want: "@babel/code-frame"},
		{name: "quoted scoped", specKey: `"@babel/code-frame@^7.12.13"`, want: "@babel/code-frame"},
		{name: "github shorthand", specKey: "tooling@webpack/tooling#v1.26.4", want: "tooling"},
		{name: "quoted git url", specKey: `"libsignal@git+https://github.com/adiwajshing/libsignal-node.git"`, want: "libsignal"},
		{name: "no range at all", specKey: "lodash", want: "lodash"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := packageName(tt.specKey); got != tt.want {
				t.Errorf("packageName(%q) = %q, want %q", tt.specKey, got, tt.want)
			}
		})
	}
}

func TestGitReference(t *testing.T) {
	tests := []struct {
		name     string
		resolved string
		want     string
	}{
		{
			name:     "explicit git+https protocol with commit fragment",
			resolved: "git+https://github.com/adiwajshing/libsignal-node.git#11dbd962ea108187c79a7c46fe4d6f790e23da97",
			want:     "11dbd962ea108187c79a7c46fe4d6f790e23da97",
		},
		{
			name:     "plain git:// protocol with commit fragment",
			resolved: "git://github.com/foo/bar.git#abcdef1234567890abcdef1234567890abcdef12",
			want:     "abcdef1234567890abcdef1234567890abcdef12",
		},
		{
			name:     "github shorthand codeload tarball",
			resolved: "https://codeload.github.com/webpack/tooling/tar.gz/978dc1c9680ef7d79f5f5c02c3439385d7937c39",
			want:     "978dc1c9680ef7d79f5f5c02c3439385d7937c39",
		},
		{
			name:     "registry tarball's trailing hash is a checksum, not a reference",
			resolved: "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c564c3bffaae8454cf0b3df370c3d6911c",
			want:     "",
		},
		{
			name:     "git URL without a commit fragment",
			resolved: "git+https://github.com/foo/bar.git",
			want:     "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := gitReference(tt.resolved); got != tt.want {
				t.Errorf("gitReference(%q) = %q, want %q", tt.resolved, got, tt.want)
			}
		})
	}
}

func TestSplitNameAndLocator(t *testing.T) {
	tests := []struct {
		name        string
		resolution  string
		wantName    string
		wantLocator string
	}{
		{name: "unscoped registry", resolution: "lodash@npm:4.17.21", wantName: "lodash", wantLocator: "npm:4.17.21"},
		{name: "scoped registry", resolution: "@algolia/autocomplete-core@npm:1.17.9", wantName: "@algolia/autocomplete-core", wantLocator: "npm:1.17.9"},
		{
			name:        "git locator",
			resolution:  "underscore@https://github.com/jashkenas/underscore.git#commit=cbb48b79fc1205aa04feb03dbc055cdd28a12652",
			wantName:    "underscore",
			wantLocator: "https://github.com/jashkenas/underscore.git#commit=cbb48b79fc1205aa04feb03dbc055cdd28a12652",
		},
		{name: "quoted", resolution: `"lodash@npm:4.17.21"`, wantName: "lodash", wantLocator: "npm:4.17.21"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			gotName, gotLocator := splitNameAndLocator(tt.resolution)
			if gotName != tt.wantName {
				t.Errorf("splitNameAndLocator(%q) name = %q, want %q", tt.resolution, gotName, tt.wantName)
			}
			if gotLocator != tt.wantLocator {
				t.Errorf("splitNameAndLocator(%q) locator = %q, want %q", tt.resolution, gotLocator, tt.wantLocator)
			}
		})
	}
}

func TestGitCommitFromLocator(t *testing.T) {
	tests := []struct {
		name    string
		locator string
		want    string
	}{
		{name: "git locator with commit marker", locator: "https://github.com/jashkenas/underscore.git#commit=cbb48b79fc1205aa04feb03dbc055cdd28a12652", want: "cbb48b79fc1205aa04feb03dbc055cdd28a12652"},
		{name: "registry locator has no commit marker", locator: "npm:4.17.21", want: ""},
		{name: "empty locator", locator: "", want: ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := gitCommitFromLocator(tt.locator); got != tt.want {
				t.Errorf("gitCommitFromLocator(%q) = %q, want %q", tt.locator, got, tt.want)
			}
		})
	}
}

func TestSortByName(t *testing.T) {
	packages := []lockfile.Package{
		{Name: "foo", Version: "2.0.0"},
		{Name: "bar", Version: "1.0.0"},
		{Name: "foo", Version: "1.0.0"},
	}

	sortByName(packages)

	want := []lockfile.Package{
		{Name: "bar", Version: "1.0.0"},
		{Name: "foo", Version: "1.0.0"},
		{Name: "foo", Version: "2.0.0"},
	}

	assertPackagesEqual(t, "packages", packages, want)
}

func assertPackagesEqual(t *testing.T, field string, got, want []lockfile.Package) {
	t.Helper()

	if len(got) != len(want) {
		t.Fatalf("%s length = %d, want %d (got %#v)", field, len(got), len(want), got)
	}

	for i := range want {
		if got[i] != want[i] {
			t.Errorf("%s[%d] = %#v, want %#v", field, i, got[i], want[i])
		}
	}
}
