// Package report renders a dependencydiff.Report for its two audiences: the
// Markdown body of the Bot Comment (Render), and plain terminal text for a
// Local Comparison (RenderText) — see CONTEXT.md. The Bot Comment is the
// single comment the bot maintains on a Change Request, identified by a
// hidden marker and updated in place on every pipeline run; a Local
// Comparison instead prints to the terminal and posts nothing.
package report

import (
	"fmt"
	"strings"

	"github.com/jdecool/dependency-diff-notes/internal/dependencydiff"
)

// Marker is a hidden HTML comment identifying a note as the bot's own,
// so the bot can find and update it instead of creating a duplicate.
const Marker = "<!-- dependency-diff-notes -->"

// shortRefLength is how many leading characters of a reference (a Git commit
// hash) are shown, mirroring the short hash format Git itself uses.
const shortRefLength = 7

// Render renders r into the full Markdown body of the Bot Comment,
// including the leading Marker.
func Render(r dependencydiff.Report) string {
	var b strings.Builder

	b.WriteString(Marker)
	b.WriteString("\n## Dependency changes\n")

	if r.IsEmpty() {
		b.WriteString("\nNo dependency changes detected.\n")
		return b.String()
	}

	for _, s := range r.Sections {
		if s.IsEmpty() {
			continue
		}

		fmt.Fprintf(&b, "\n### %s\n", s.Ecosystem)

		if len(s.Combined) > 0 {
			b.WriteString("\n#### Dependencies\n")
			writeChanges(&b, s.Combined)
			continue
		}

		if len(s.Production) > 0 {
			b.WriteString("\n#### Production dependencies\n")
			writeChanges(&b, s.Production)
		}

		if len(s.Development) > 0 {
			b.WriteString("\n#### Development dependencies\n")
			writeChanges(&b, s.Development)
		}
	}

	return b.String()
}

// RenderText renders r as a plain-text Dependency Report for a terminal (see
// CONTEXT.md: Local Comparison), grouped by Ecosystem then Production /
// Development (or a single Dependencies group), with +/-/~ markers for added,
// removed, and updated packages. Unlike Render it carries no hidden marker and
// no Markdown, since it is printed to the terminal rather than posted as a Bot
// Comment.
func RenderText(r dependencydiff.Report) string {
	var b strings.Builder

	b.WriteString("Dependency changes\n")

	if r.IsEmpty() {
		b.WriteString("\nNo dependency changes detected.\n")
		return b.String()
	}

	for _, s := range r.Sections {
		if s.IsEmpty() {
			continue
		}

		fmt.Fprintf(&b, "\n%s\n", s.Ecosystem)

		if len(s.Combined) > 0 {
			writeTextGroup(&b, "Dependencies", s.Combined)
			continue
		}

		if len(s.Production) > 0 {
			writeTextGroup(&b, "Production dependencies", s.Production)
		}

		if len(s.Development) > 0 {
			writeTextGroup(&b, "Development dependencies", s.Development)
		}
	}

	return b.String()
}

// writeTextGroup renders one section's changes for RenderText under an
// indented group title. changes is assumed already grouped in the order
// guaranteed by dependencydiff.Diff (Added, then Updated, then Removed,
// alphabetical within each group); it is not re-sorted here.
func writeTextGroup(b *strings.Builder, title string, changes []dependencydiff.Change) {
	fmt.Fprintf(b, "  %s\n", title)

	for _, c := range changes {
		b.WriteString(renderChangeText(c))
		b.WriteString("\n")
	}
}

// renderChangeText renders a single Change as one plain-text line for
// RenderText.
func renderChangeText(c dependencydiff.Change) string {
	switch c.Type {
	case dependencydiff.Added:
		return fmt.Sprintf("    + %s  %s", c.Name, formatVersionRef(c.ToVersion, c.ToReference))
	case dependencydiff.Removed:
		return fmt.Sprintf("    - %s  %s", c.Name, formatVersionRef(c.FromVersion, c.FromReference))
	case dependencydiff.Updated:
		from := formatVersionRef(c.FromVersion, c.FromReference)
		to := formatVersionRef(c.ToVersion, c.ToReference)
		return fmt.Sprintf("    ~ %s  %s -> %s", c.Name, from, to)
	default:
		return fmt.Sprintf("    %s", c.Name)
	}
}

// HasMarker reports whether body was previously generated by Render (i.e.
// contains Marker), used by the orchestrator to find the bot's existing
// comment among all comments on a Change Request.
func HasMarker(body string) bool {
	return strings.Contains(body, Marker)
}

// writeChanges renders one section's changes, grouped by ChangeType under a
// bold label. changes is assumed to already be grouped in the order
// guaranteed by dependencydiff.Diff (Added, then Updated, then Removed,
// alphabetical within each group); it is not re-sorted here.
func writeChanges(b *strings.Builder, changes []dependencydiff.Change) {
	var currentType dependencydiff.ChangeType

	inGroup := false

	for _, c := range changes {
		if !inGroup || c.Type != currentType {
			fmt.Fprintf(b, "\n**%s**\n\n", groupLabel(c.Type))
			currentType = c.Type
			inGroup = true
		}

		b.WriteString(renderChange(c))
		b.WriteString("\n")
	}
}

// groupLabel returns the section label for a ChangeType group.
func groupLabel(t dependencydiff.ChangeType) string {
	switch t {
	case dependencydiff.Added:
		return "Added"
	case dependencydiff.Updated:
		return "Updated"
	case dependencydiff.Removed:
		return "Removed"
	default:
		return "Unknown"
	}
}

// renderChange renders a single Change as one Markdown list item.
func renderChange(c dependencydiff.Change) string {
	name := nameMarkdown(c)

	switch c.Type {
	case dependencydiff.Added:
		return fmt.Sprintf("- %s: added %s", name, formatVersionRef(c.ToVersion, c.ToReference))
	case dependencydiff.Removed:
		return fmt.Sprintf("- %s: removed %s", name, formatVersionRef(c.FromVersion, c.FromReference))
	case dependencydiff.Updated:
		from := formatVersionRef(c.FromVersion, c.FromReference)
		to := formatVersionRef(c.ToVersion, c.ToReference)
		return fmt.Sprintf("- %s: %s → %s", name, from, to)
	default:
		return fmt.Sprintf("- %s", name)
	}
}

// nameMarkdown renders a Change's package name, as a Markdown link to
// SourceURL when available, or as plain text otherwise.
func nameMarkdown(c dependencydiff.Change) string {
	if c.SourceURL == "" {
		return c.Name
	}

	return fmt.Sprintf("[%s](%s)", c.Name, c.SourceURL)
}

// formatVersionRef renders a version, appending its short reference in
// parentheses when ref is non-empty so a Reference Change (see CONTEXT.md)
// on a package whose version label doesn't change (typical of dev-*
// branches) is still visible.
func formatVersionRef(version, ref string) string {
	if ref == "" {
		return version
	}

	return fmt.Sprintf("%s (%s)", version, shortRef(ref))
}

// shortRef truncates a reference to shortRefLength characters, mirroring the
// short hash format Git itself uses. References shorter than that are
// returned unchanged.
func shortRef(ref string) string {
	if len(ref) > shortRefLength {
		return ref[:shortRefLength]
	}

	return ref
}
